#!/usr/bin/env perl
use strict;
use warnings;
use diagnostics;
use feature 'say';
use feature 'switch';

my $file;
open($file, "<", "./return_2.c") or die "Cannot Open file";

my $line_number = 1;


my $token = undef;
while (<$file>) {
    my $line = $_;

    while (substr($line, 0, 1) ne '\n') {
        ($token) = ($line =~ /(\(|\)|\{|\}|;|\w*)/);

        if ($token ne '') {
            print("token: '$token'\n");
            $line = substr($line, length($token), length($line));
        }  else {
            my $front_empty = undef;
            ($front_empty) = ($line =~ /^\s*/);
            if (length($line) == length($front_empty)) {
                last;
            }
            $line = substr($line, length($front_empty), length($line));
            next;
        }

        my $identifier= undef;
        my $constant = undef;
        ($identifier) = ($line =~ /([a-zA-Z_]\w*\b)/g);
        ($constant) = ($line =~ /([0-9]+\b)/);

        if (defined $identifier) {
            print("identifier: ", $identifier, "\n")
        }
        if (defined $constant) {
            print("constant: ", $constant, "\n")
        }

    }

    $line_number++;
}
