#!/usr/bin/env perl
#
# TODO:
# - get file path from ARGV[0] for executable to be build in
# - handle command line arguments
# - return proper errors with non zero exit codes
#
use strict;
use warnings;
use diagnostics;
use feature 'say';
use feature 'switch';

my $fp;
my $c_file = $ARGV[-1];
my $option_flags = 0;
my $options = { 'lex' => 1 << 0, 'parse' => 1 << 1, 'codegen' => 1 << 2 };

for my $i (0 .. $#ARGV) {
    my $arg = $ARGV[$i];
    if ($arg =~ /^--/) {
        $option_flags |= $options->{lex};
    }
}

open($fp, "<", $c_file) or die "Cannot Open file";

my $line_number = 1;


my $token = undef;
while (<$fp>) {
    my $line = $_;

    while (substr($line, 0, 1) ne '\n') {
        ($token) = ($line =~ /(\(|\)|\{|\}|;|\w*)/);

        if ($token ne '') {
            print("token: '$token'\n");
            $line = substr($line, length($token), length($line));
        }  else {
            my $front_empty = undef;
            ($front_empty) = ($line =~ /^\s*/);
            if (length($line) == length($front_empty)) {
                last;
            }
            $line = substr($line, length($front_empty), length($line));
            next;
        }

        my $identifier= undef;
        my $constant = undef;
        ($identifier) = ($line =~ /([a-zA-Z_]\w*\b)/g);
        ($constant) = ($line =~ /([0-9]+\b)/);

        if (defined $identifier) {
            print("identifier: ", $identifier, "\n")
        }
        if (defined $constant) {
            print("constant: ", $constant, "\n")
        }

    }

    $line_number++;
}
